### ISSUE TITLE
IOTA and Ripple support would be amazing!

### ISSUE THREAD

**Issue by kdthomas2121** [T-Pham/CoinPriceBar#1]

**Comment by T-Pham** [comment]
Yup! I plan to add more coins support and allow user customization.
But as in any other open-source projects, your PRs are always welcome.

**Comment by T-Pham** [comment]
@kdthomas2121 Ripple support has been added in version 1.2.

**Comment by T-Pham** [comment]
Support for IOTA has been added in version 1.3.
