### ISSUE TITLE
XRP IOTA and ADA no longer working

### ISSUE THREAD

**Issue by kdthomas2121** [T-Pham/CoinPriceBar#14]
Just displaying as "XRP   IOTA     ADA" on my machine. Every other coin is working

**Comment by T-Pham** [comment]
Those coins' prices are fetched from Binance. Their server is down atm.

**Comment by carygeo** [comment]
./CoinPriceBar/BinancePriceProvider.swift:12:    let url = URL(string: "https://www.binance.com/api/v1/ticker/allPrices")!

That Binance price url no longer works after recent Binance server updates.  Use this one below:
https://us.binance.com/api/v1/ticker/allPrices

**Comment by T-Pham** [comment]
The server has worked again.
Closing the issue.
