### ISSUE TITLE
wondering if you can make a modified version for me?

### ISSUE THREAD

**Issue by bomed** [T-Pham/CoinPriceBar#16]
could you make a version that is in Canadian fiat. and has Bitcoin, Ethereum, Litecoin , Monero, zilliqa, stellar lumens, Cardano, ark, polymath. that would make my Touch Bar actually very useful. I would be very grateful. thank you so very much for you talents and what you contribute without talents like yours helping out the world would be a whole lot shittier. 

cheers

cam

**Comment by T-Pham** [comment]
@bomed here you go 
https://github.com/T-Pham/CoinPriceBar/releases/download/1.5.0.16/CoinPriceBar.app.zip

Polymath is not listed on Binance so I couldn't add it.
