### ISSUE TITLE
Make it easy to build

### ISSUE THREAD

**Issue by marceloboeira** [T-Pham/CoinPriceBar#17]
Can you add instructions on how to build or even better a Makefile?

Since you're not supporting much, it's easier for other people to just fork build and use on their own currencies/coins... 

Thanks!

**Comment by T-Pham** [comment]
Hi 👋,

Actually, things are usually really standard when it comes to Mac app development. You will just need to open the project in XCode and build it!

Cheers,

**Comment by marceloboeira** [comment]
Great!
