### ISSUE TITLE
CZK fiat

### ISSUE THREAD

**Issue by tombarys** [T-Pham/CoinPriceBar#2]
Could you add CZK as a fiat currency, please? Thanks in advance!
Tomáš

**Comment by T-Pham** [comment]
I planned to create a settings page where users can choose their preferred currency and coins but I will only be able to work on it once I have more time.
For now, I've built a version with the currency set to CZK. You can download it [here](https://github.com/T-Pham/CoinPriceBar/releases/download/1.3.0.2/CoinPriceBar.app.zip).

**Comment by tombarys** [comment]
THANKS, Thanh!

Tomáš

út 2. 1. 2018 v 16:56 odesílatel Thanh Pham <notifications@github.com>
napsal:
