### ISSUE TITLE
Feature request: downgrade to osx 10.12.x?

### ISSUE THREAD

**Issue by Gargo** [T-Pham/CoinPriceBar#3]
Reasons:
1)even latest MacBooks pro (2017) come with preinstalled 10.12.6, NOT 10.13.x
2)10.13.x is very unstable
3)touchbar is available since 10.12.2

I tried to decrease the minimum version only but it causes a crash without console log. The possible reasons:
1)10.12.6
2)my MacBook Pro hasn't touchbar (BUT Xcode can simulate it)

**Comment by T-Pham** [comment]
@Gargo thanks for the info you provided.
I wanted to support earlier OS X versions but I couldn't find a way to test the app on those versions. My Mac is already on 10.13.
If you have a Mac running 10.12, can you please help me check if the `DFRFoundation.framework` is located at `/System/Library/PrivateFrameworks/`? I cannot think of any other reason for the crash right now.

**Comment by jmauzy** [comment]
I can confirm this file is NOT present on my 10.12.6 install.

**Comment by plimpton** [comment]
It's not on my 10.12.6 system either :(
