### ISSUE TITLE
Add EUR Currency

### ISSUE THREAD

**Issue by Th3Mouk** [T-Pham/CoinPriceBar#6]
Can u please add EUR currency ? Or add a quick tuto how to build and test.

Thanks

**Comment by T-Pham** [comment]
You can change the fiat currency by adding it to `FiatMoney` enum in `CoinPriceBar/Money.swift` and change `currency` from `.USD` to that currency in `CoinPriceBar/Data.swift`.
That should be similar to the below commit, in which I changed USD to CZK.
https://github.com/T-Pham/CoinPriceBar/commit/1b755d7a9df5d5da8fab8f8cdf9c7e1d4b66ff2f

**Comment by Th3Mouk** [comment]
Thank you, it's not usefull yet to make a PR.

**Comment by Th3Mouk** [comment]
EURO fork: https://github.com/Th3Mouk/CoinPriceBar
I will maintain as long as necessary
