### ISSUE TITLE
How to modify the icon displayed on Touchbar

### ISSUE THREAD

**Issue by littp** [T-Pham/CoinPriceBar#7]
now
![image](https://user-images.githubusercontent.com/15848626/34552149-cad8b18e-f15a-11e7-91dc-2895804001b4.png)

I want
![image](https://user-images.githubusercontent.com/15848626/34552180-f205204e-f15a-11e7-89fd-9af67bc8f68b.png)

**Comment by T-Pham** [comment]
Let me show you how.
Looking at the file `Data.swift`, you will see the `supportedCoins` variable, which is a list of coins which will be displayed.
https://github.com/T-Pham/CoinPriceBar/blob/master/CoinPriceBar/Data.swift#L9
You can remove any coins that you don't want to be displayed then build your own version.

However, if you are not familiar with Swift or MacOS app development, feel free to let me know so I can help you build it.

**Comment by littp** [comment]
modify  and rebuild ?

**Comment by T-Pham** [comment]
yes

**Comment by littp** [comment]
@T-Pham  thank you . i try
