### ISSUE TITLE
How to change the currency from $ to € and other Exchange like ie. kraken.com

### ISSUE THREAD

**Issue by chpe** [T-Pham/CoinPriceBar#8]

**Comment by T-Pham** [comment]
To change the currency, you can do similar to the commit https://github.com/T-Pham/CoinPriceBar/commit/1b755d7a9df5d5da8fab8f8cdf9c7e1d4b66ff2f, in which I changed USD to CZK. There is also a fork where curency is set to EUR mentioned at #6.

To add another Exchange, you will need to write a class conform to `CoinPriceProvider` protocol. You can find an example in #5 where Bittrex is added as a `CoinPriceProvider`.

Feel free to let me know if you need more help.
