### ISSUE TITLE
prices are different

### ISSUE THREAD

**Issue by iln0892** [T-Pham/CoinPriceBar#9]
The prices are from Coinbase.
how can I show the prices from Coinmarketcap ?

**Comment by T-Pham** [comment]
To add another Exchange, you will need to write a class conform to CoinPriceProvider protocol. You can find an example in #5 where Bittrex is added as a CoinPriceProvider.

Feel free to let me know if you need more help.

**Comment by iln0892** [comment]
Thank you.
What you think about the Features:

- Coloring Red / Green for up and downs
- Sliding left and right with finger (when more than 5/6 cryptos added)
- when pressing to one crypto, it changes from example -> 13000.01$ to -> +2,35% or -2,35%
- 2 Options as Menu (1st -> Top 10 Coinmarketcap.com / 2nd the own cryptos)
- Possibility for adding the (exchange API KEY) to listing the wallets from exchange

**Comment by T-Pham** [comment]
Thanks for your suggestions @iln0892.
I will consider adding these if I have more time in the future and if bitcoin ever becomes hot again ;)
